# Generated by Django 3.0 on 2021-03-28 15:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='student',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='has_homework',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='lesson',
        ),
        migrations.AlterField(
            model_name='homework',
            name='date_assigned',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='homework',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EndUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(max_length=500, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('grade', models.CharField(max_length=20, null=True)),
                ('color', models.CharField(choices=[('#000000', 'Black'), ('#0C090A', 'Night'), ('#2C3539', 'Gunmetal'), ('#2B1B17', 'Midnight'), ('#34282C', 'Charcoal'), ('#25383C', 'Dark Slate Gray'), ('#3B3131', 'Oil'), ('#413839', 'Black Cat'), ('#3D3C3A', 'Iridium'), ('#463E3F', 'Black Eel'), ('#6698FF', 'Sky Blue')], default='#000000', max_length=25)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('is_student', models.BooleanField(default=True)),
                ('is_teacher', models.BooleanField(default=False)),
                ('homework', models.ManyToManyField(blank=True, related_name='user_homework', to='classes.Homework')),
                ('lesson', models.ManyToManyField(blank=True, related_name='user_lesson', to='classes.Lesson')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_grade', to='classes.EndUser'),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('student', 'grade')},
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
